// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsjfsZkbacf3jhZiNZsaomGL2WWBxBjw',
    appId: '1:568198726125:web:895757f16b31fff336a7e4',
    messagingSenderId: '568198726125',
    projectId: 'recycle-app-447304',
    authDomain: 'recycle-app-447304.firebaseapp.com',
    storageBucket: 'recycle-app-447304.firebasestorage.app',
    measurementId: 'G-K92S3LX2TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYPgCS9U3Pg4AoqDGTaj4b9yOAGOUD1o',
    appId: '1:568198726125:android:a21fe0eae63ca1fc36a7e4',
    messagingSenderId: '568198726125',
    projectId: 'recycle-app-447304',
    storageBucket: 'recycle-app-447304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSJGd_rwQwRupNhg2oZR6AN7CDaP9xsY',
    appId: '1:568198726125:ios:0895ce86808049c836a7e4',
    messagingSenderId: '568198726125',
    projectId: 'recycle-app-447304',
    storageBucket: 'recycle-app-447304.firebasestorage.app',
    androidClientId: '568198726125-7l6aavf28q0fijvg7chm2a1lohh6p2a4.apps.googleusercontent.com',
    iosClientId: '568198726125-3092s05j96dt4boc634d5f78n5s550d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.landingPageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSJGd_rwQwRupNhg2oZR6AN7CDaP9xsY',
    appId: '1:568198726125:ios:0895ce86808049c836a7e4',
    messagingSenderId: '568198726125',
    projectId: 'recycle-app-447304',
    storageBucket: 'recycle-app-447304.firebasestorage.app',
    androidClientId: '568198726125-7l6aavf28q0fijvg7chm2a1lohh6p2a4.apps.googleusercontent.com',
    iosClientId: '568198726125-3092s05j96dt4boc634d5f78n5s550d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.landingPageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsjfsZkbacf3jhZiNZsaomGL2WWBxBjw',
    appId: '1:568198726125:web:f5bfec23218f938a36a7e4',
    messagingSenderId: '568198726125',
    projectId: 'recycle-app-447304',
    authDomain: 'recycle-app-447304.firebaseapp.com',
    storageBucket: 'recycle-app-447304.firebasestorage.app',
    measurementId: 'G-CWWHTKL4BS',
  );

}